### ISSUE TITLE
amCharts - TS improvements

### ISSUE THREAD

**Issue by maneetgoyal** [lakshya-aggarwal/manufac-scatter-plot#1]
Overall, a good job 👍. 

---

Suggesting some further improvements.

1. Folder structure can be improved:

<img width="226" alt="Screenshot 2020-10-30 at 10 55 47 PM" src="https://user-images.githubusercontent.com/25290212/97737528-25534c80-1b03-11eb-8d58-37b90a8abe78.png">

Suggest reserving the `dist` folder for build output ONLY. The `index.html`, data (.JSON), CSS, etc. should be placed in `src`. Post build, a `dist` folder should be created which contains the ready-to-deploy app including *all** the necessary resources like the compiled JS file, `index.html`, CSS, .JSON, etc. `html-webpack-plugin` can be used to achieve this goal.

2. Seeing some redundant dependencies:

```
    "clean-webpack-plugin": "^3.0.0",
    "express": "^4.17.1",
    "html-webpack-plugin": "^4.5.0",
    "webpack-dev-middleware": "^4.0.0",
```

`clean-webpack-plugin` is useful during `watch` mode but is unused at the moment.

Suggest using whatever you can if it adds value to the project, else consider removing the redundant dependencies.

Similarly, is `"@amcharts/amcharts4-fonts": "^4.0.1"` needed?

3. Can the use of inline CSS be replaced with some kind of property assignment?

Instead of

```ts
bullet.tooltipText = "Color Intesity: {valueY}\n[bold font-size: 17px]Malic Acid: {valueX}[/]";
```

something like:

```ts
bullet.tooltipText = "Color Intesity: {valueY}\n Malic Acid: {valueX}";
bullet.xyz.abc = "17px"; // Will need to find out if such a property exists by looking at their docs.
```

4. The following looks like very specific details. Some comments will be useful for future readers:

```
reg.simplify = true;
reg.reorder = true;
```

5. Use of [templates literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) can look a bit more readable as compared to string concatenation:

```
label.text = "[bold]Equation:[/] " + ev.target.result.string.replace(/\^2/, "²") + "\n[bold]R² :[/] " + ev.target.result.r2;
```

Also I am a bit unsure why `ev.target.result.string.replace(/\^2/, "²")` is used. The trend line is linear but the `.replace` logic seems to be useful when we have a polynomial trend line. 

---

**Comment by maneetgoyal** [comment]
@lakshya-aggarwal

**Comment by lakshya-aggarwal** [comment]
@maneetgoyal Hey, I have resolved issues 1,2,4 and 5. Checking if no.3 is feasible. Please review.

**Comment by lakshya-aggarwal** [comment]
@maneetgoyal For point 3, we do have something like:
`label.fontWeight = "bold";`
But this applies the property to entire text, not selectively.
I have used it in one place for the equation and not for the bullet tooltip on hover for the time being.

**Comment by maneetgoyal** [comment]
Looking good @lakshya-aggarwal.

Noticed 1 issue: the script tag is getting duplicated in the bundled output.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  <script defer src="/bundle.js"></script><link href="/main.css" rel="stylesheet"></head>
  <body>
    <div id="chartdiv"></div>
    <script src="bundle.js"></script>
  </body>
</html>
```

And don't worry about point 3. The findings so far are good enough.

**Comment by maneetgoyal** [comment]
Also a few questions:

1. What is the utility of the `.directory` file?
2. What is the source of the `.gitignore` file?
3. The CSS is using both `hsl` and `hexadecimal` notations for representing colour. Is there any reason behind this differential usage? For reference:

```css
body { 
    background-color: hsl(0, 0%, 0%); 
    color: #fff;
}
```

**Comment by lakshya-aggarwal** [comment]
> Also a few questions:
> 
> 1. What is the utility of the `.directory` file?
> 2. What is the source of the `.gitignore` file?
> 3. The CSS is using both `hsl` and `hexadecimal` notations for representing colour. Is there any reason behind this differential usage? For reference:
> 
> ```css
> body { 
>     background-color: hsl(0, 0%, 0%); 
>     color: #fff;
> }
> ```

@maneetgoyal
1. Generated by default by browser in my linux system. Have added it to the the gitignore. Will be removed in the next iteration.
2. I assembled the gitignore from various node.js projects on github. Can be updated as required.
3. No technical reason. I was trying out various formats for myself.

**Comment by lakshya-aggarwal** [comment]
> Looking good @lakshya-aggarwal.
> 
> Noticed 1 issue: the script tag is getting duplicated in the bundled output.
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="UTF-8" />
>   <script defer src="/bundle.js"></script><link href="/main.css" rel="stylesheet"></head>
>   <body>
>     <div id="chartdiv"></div>
>     <script src="bundle.js"></script>
>   </body>
> </html>
> ```
> 
> And don't worry about point 3. The findings so far are good enough.

Updated index.html

**Comment by maneetgoyal** [comment]
LGTM. Please consider the issue resolved.
